<?php

/**
 * @file
 * Contains custom_layout_builder hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * Adds help page that describes purpose and functionality of the module.
 *
 * @see hook_help()
 */
function custom_layout_builder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.custom_layout_builder':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module extends core Layout Builder module to provide custom functionality.') . '</p>';
      $output .= '<p>' . t('It adds custom layouts which allow us to add classes to the wrapper and regions.') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_preprocess_HOOK() for layout_onecol.
 */
function custom_layout_builder_preprocess_layout_twocol(&$variables) {
  // Attach the library.
  $variables['#attached']['library'][] = 'custom-layout-builder';
}
